version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_seckill
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - course_seckill_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - course_seckill_network

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - course_seckill_network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT: 30000
    depends_on:
      - zookeeper
    networks:
      - course_seckill_network

networks:
  course_seckill_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  kafka_data:
  zookeeper_data: 
